# This file is used to create a MySQL container with a database named messenger
version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql_aidesign
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: messenger
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:

networks:
  default:
    driver: bridge
